using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ITI.SMS.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AutoGeneratedPendingChanges : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "f_k_courses_users_instructor_id",
                table: "courses");

            migrationBuilder.RenameColumn(
                name: "instructor_id",
                table: "courses",
                newName: "lecturer_id");

            migrationBuilder.RenameIndex(
                name: "i_x_courses_instructor_id",
                table: "courses",
                newName: "i_x_courses_lecturer_id");

            migrationBuilder.Sql("DELETE FROM lab_evaluations");

            migrationBuilder.AddColumn<string>(
                name: "evaluator_id",
                table: "lab_evaluations",
                type: "nvarchar(450)",
                nullable: false,
                defaultValue: "");

            migrationBuilder.CreateTable(
                name: "course_lab_assistants",
                columns: table => new
                {
                    course_id = table.Column<int>(type: "int", nullable: false),
                    instructor_id = table.Column<string>(type: "nvarchar(450)", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("p_k_course_lab_assistants", x => new { x.course_id, x.instructor_id });
                    table.ForeignKey(
                        name: "f_k_course_lab_assistants_courses_course_id",
                        column: x => x.course_id,
                        principalTable: "courses",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "f_k_course_lab_assistants_users_instructor_id",
                        column: x => x.instructor_id,
                        principalTable: "users",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "i_x_lab_evaluations_evaluator_id",
                table: "lab_evaluations",
                column: "evaluator_id");

            migrationBuilder.CreateIndex(
                name: "i_x_course_lab_assistants_instructor_id",
                table: "course_lab_assistants",
                column: "instructor_id");

            migrationBuilder.AddForeignKey(
                name: "f_k_courses_users_lecturer_id",
                table: "courses",
                column: "lecturer_id",
                principalTable: "users",
                principalColumn: "id",
                onDelete: ReferentialAction.SetNull);

            migrationBuilder.AddForeignKey(
                name: "f_k_lab_evaluations_users_evaluator_id",
                table: "lab_evaluations",
                column: "evaluator_id",
                principalTable: "users",
                principalColumn: "id");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "f_k_courses_users_lecturer_id",
                table: "courses");

            migrationBuilder.DropForeignKey(
                name: "f_k_lab_evaluations_users_evaluator_id",
                table: "lab_evaluations");

            migrationBuilder.DropTable(
                name: "course_lab_assistants");

            migrationBuilder.DropIndex(
                name: "i_x_lab_evaluations_evaluator_id",
                table: "lab_evaluations");

            migrationBuilder.DropColumn(
                name: "evaluator_id",
                table: "lab_evaluations");

            migrationBuilder.RenameColumn(
                name: "lecturer_id",
                table: "courses",
                newName: "instructor_id");

            migrationBuilder.RenameIndex(
                name: "i_x_courses_lecturer_id",
                table: "courses",
                newName: "i_x_courses_instructor_id");

            migrationBuilder.AddForeignKey(
                name: "f_k_courses_users_instructor_id",
                table: "courses",
                column: "instructor_id",
                principalTable: "users",
                principalColumn: "id",
                onDelete: ReferentialAction.SetNull);
        }
    }
}
